-- ==========================================
-- CREACIÓN DE LA TABLA pagos_recibidos_mp
-- Ejecutar este script en el editor SQL de Supabase (SQL Editor)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.pagos_recibidos_mp (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mp_payment_id text NOT NULL UNIQUE,
  monto numeric(10, 2) NOT NULL,
  payer_name text,
  payer_document text,
  concepto text,
  fecha_acreditacion timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  presupuesto_id bigint REFERENCES public.presupuestos(id) ON DELETE SET NULL
);

-- Comentario explicativo de las columnas:
COMMENT ON COLUMN public.pagos_recibidos_mp.mp_payment_id IS 'ID del pago provisto por Mercado Pago';
COMMENT ON COLUMN public.pagos_recibidos_mp.monto IS 'El importe bruto transferido';
COMMENT ON COLUMN public.pagos_recibidos_mp.payer_name IS 'Nombre completo del titular que transfiere';
COMMENT ON COLUMN public.pagos_recibidos_mp.payer_document IS 'DNI/CUIT/CUIL del titular';
COMMENT ON COLUMN public.pagos_recibidos_mp.concepto IS 'Concepto o referencia textual ingresado por el emisor';
COMMENT ON COLUMN public.pagos_recibidos_mp.presupuesto_id IS 'ID del presupuesto asociado en Queselló';
